name: PVPGradingGo!
version: 1.0.1_beta
main: org\hypergo\PVPGradingGo\Main
load: POSTWORLD
author: dhdj,HypergoStdio(xMing)
api:
- 1.0.0
- 2.0.0
- 3.0.0
- 4.0.0
commands:
  getrank:
    description: "查询段位指令"
    permission: getrank.command
permissions:
  getrank.command: 
    default: true